### PR TITLE
add .editorconfig file, exported from php_style.xml phpstorm

### LINKED ISSUE #782: Add .editorconfig file for consistent code style between different editors
The README defines a `php_style.xml` for JetBrains `phpstorm` IDE, however when using e.g.: `vscode`, a missing `.editorconfig` file can lead to windows developers accidently rewriting all files with LF line endings to CRLF. Devcontainer don't work on my side when CRLF are used.

I propose to import `php_style.xml` to `phpstorm` and export the styling to `.editorconfig`.

### PR DESCRIPTION
**Pull request by robinduerhager**
Closes #782 . All values are exported from the provided `php_style.xml` file of the project via the Jetbrains `phpstorm` IDE. However the `end_of_line = lf` line was set to CRLF and had to be set to lf manually.

### CODE REVIEW

**Comment by zyronix** [comment]
Looks good, but could you please add the editorconfig extension to the exentions installed for the devcontainer:
.devcontainer/devcontainer.json
```
	"extensions": [
		"xdebug.php-debug",
		"bmewburn.vscode-intelephense-client",
	],
```
Please add: EditorConfig.EditorConfig

**Review by zyronix — CHANGES_REQUESTED** [review]
Please see my other comment.

**Comment by robinduerhager** [comment]
Done 👌

**Review by zyronix — APPROVED** [review]

**Comment by zyronix** [comment]
Thanks!

**Pull request merged**
