### PR TITLE
Fix description of hash type 1430

### PR DESCRIPTION
**Pull request by zyronix**
As per discord, the description for hashmode 1430 is wrong:

image

image

@s3inlc how shall we deal with this? I can create an update call to compare the description of this hashtype, or shall we only fix this for new installs like this pull requests does?

### CODE REVIEW

**Comment by s3inlc** [comment]
I think it would be safe to also check this in the update scripts. We could even only change it, if it is exactly the wrong value (so we can be sure it was not changed already)

**Comment by s3inlc** [comment]
Oh and 1440 is wrong as well @zyronix

**Review by rickvanderzwet — APPROVED** [review]

**Review by rickvanderzwet — CHANGES_REQUESTED** [review]
Revert testing 'Approve' workflow test

**Comment by zyronix** [comment]
@s3inlc looks good, but because I created it; I cannot approve it. Please approve and merge.

**Comment by s3inlc** [comment]
> @s3inlc looks good, but because I created it; I cannot approve it. Please approve and merge.

Thanks for the feedback, as I did some of the changes I wanted you to have a look at it. Will therefore approve and merge.

**Review by s3inlc — APPROVED** [review]

**Pull request merged**
